### ISSUE TITLE
pip install tweetnlp -> UnicodeDecodeError: 'charmap'

### ISSUE THREAD

**Issue by cibernicola** [cardiffnlp/tweetnlp#1]
Trying to pip install I get this error:

Windows 10 64 - Spanish
Python 3.8 

pip install tweetnlp
`Collecting tweetnlp
  Using cached tweetnlp-0.0.8.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "XXXXXX\AppData\Local\Temp\pip-install-z3zj14sa\tweetnlp_eddf59379cc14f689008a08e6b2f0cb1\setup.py", line 4, in <module>
          readme = f.read()
        File "XXXXX\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3458: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

edit:

fixing issue (under previous described conditions)
setup.py, line 3, from
`with open('README.md', 'r') as f:`
to
`with open('README.md', 'r',encoding="utf-8") as f:`

now installation is working

**Comment by cibernicola** [comment]
fixing issue (under previous described conditions)
setup.py, line 3, from
`with open('README.md', 'r') as f:`
to
`with open('README.md', 'r',encoding="utf-8") as f:`

now installation is working

**Comment by asahi417** [comment]
Hi @cibernicola,

Thank you for raising the issue and proposing the solution! I will fix the code accordingly in next version soon later. We haven't tested it in Windows yet, so this is very helpful, and we really appreciate it!

Asahi
