### ISSUE TITLE
Train on my dataset

### ISSUE THREAD

**Issue by rishiwobb** [cardiffnlp/tweetnlp#13]
I want to use the cardiffnlp/tweet-topic-21-multi model from huggingface. But I want to add more labels/categories in the output. It is my understanding that I would need to manually train the model. Any guidance on how to do so?

**Comment by asahi417** [comment]
If you need a model to cover additional labels, you need first to prepare a set of tweets annotated with the labels, and fine-tune LM on your dataset. As a reference, the tweet-topic dataset consists of around 1k tweets annotated over 21 labels.
