### ISSUE TITLE
Proposal: Add Support for Apple Silicon Chips Using MPS for GPU Acceleration

### ISSUE THREAD

**Issue by sferez** [cardiffnlp/tweetnlp#15]
I'm writing to propose an enhancement that would significantly improve the efficiency of the tweetnlp library on Apple machines equipped with Apple Silicon 'new' chips, leveraging the Metal Performance Shaders (MPS) backend for GPU training acceleration.

The proposal involves a change at line 76 of the _tweetnlp/text_classification/model.py_ file to select the processing device.
_Note: I am focusing on the classification for now because it's the feature I use, but I think this change can be beneficial in other areas too._

Currently, the library checks for CUDA availability to utilize GPU acceleration:

```
# GPU setup
self.device = 'cuda' if torch.cuda.device_count() > 0 else 'cpu'
```

However, on Apple's M1 machines, CUDA is not available as they utilize Apple's in-built acceleration chips. A workaround for this is to use MPS (Metal Performance Shaders) that is supported on these M1 machines. I propose adding an additional check for MPS in the device selection process:

```
# GPU setup
if torch.cuda.is_available() and torch.cuda.device_count() > 0:
    self.device = torch.device('cuda')
elif torch.backends.mps.is_available() and torch.backends.mps.is_built():
    self.device = torch.device("mps")
else:
    self.device = torch.device('cpu')
```

This will provide an optimized computational path for users running tweetnlp on M1 machines, and fallbacks to CPU when neither CUDA nor MPS is available.

_Quick Benchmark:
On the first-generation M1, this modification resulted in reducing the classification task time by more than half, demonstrating a significant improvement in efficiency._

I believe this enhancement would benefit many users and improve the experience of using tweetnlp on the latest generation of Apple machines.

**Comment by asahi417** [comment]
Thanks for the suggestion, and I updated the library accordingly so please check if it's working properly!

**Comment by asahi417** [comment]
Please make sure that you are using tweetnlp==0.4.4 when you test it.

**Comment by sferez** [comment]
Hi,

Yes, it works on my mac, and I also tried it on Colab with a GPU too. Thanks!
