### ISSUE TITLE
ImportError: cannot import name 'OrderedDict'

### ISSUE THREAD

**Issue by keikoochoa** [cardiffnlp/tweetnlp#2]
1 import os
----> 2 from typing import (
      3     Union,
      4     Tuple,
      5     OrderedDict,

ImportError: cannot import name 'OrderedDict'

hi, not sure if anyone else has had this problem?

**Comment by asahi417** [comment]
Hi, can you share your python version? TweetNLP is available only with later version of python3, so I assume your python is either of 2 or older version of 3.
