### ISSUE TITLE
HF models are not available anymore

### ISSUE THREAD

**Issue by amishra-vn** [cardiffnlp/tweetnlp#7]
Hi Team, it seems the hugging face-hosted models are not loading from the hub. 

Is this a downtime?

**Comment by asahi417** [comment]
Hi, could you share the code to reproduce the bug with the version of tweetnlp?
thanks

**Comment by amishra-vn** [comment]
The issue is reproducible again, I am using the code provided in the model card : [cardiffnlp/twitter-xlm-roberta-base-sentiment](https://huggingface.co/cardiffnlp/twitter-xlm-roberta-base-sentiment/discussions/new). 

Code- 
`MODEL = f"cardiffnlp/twitter-xlm-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(MODEL)`

But the above error is popping up while running the code.

**Comment by asahi417** [comment]
That's very weird as it's on the huggingface https://huggingface.co/cardiffnlp/twitter-xlm-roberta-base-sentiment .

It might be something to do with the huggingface side, not the tweetnlp, but glad to hear that it's now working!
